import { useEffect, useState } from "react";
import type { Borrower } from "../data/portfolio";
import { ApiError, draftMemo } from "../api/client";
import type { MemoResponse } from "../api/types";

interface CreditMemoProps {
  borrower: Borrower;
}

type MemoState =
  | { phase: "idle" }
  | { phase: "loading" }
  | { phase: "ready"; memo: MemoResponse; approved: boolean }
  | { phase: "error"; message: string };

export function CreditMemo({ borrower }: CreditMemoProps) {
  const [state, setState] = useState<MemoState>({ phase: "idle" });

  useEffect(() => {
    setState({ phase: "idle" });
  }, [borrower.id]);

  async function generate() {
    setState({ phase: "loading" });
    try {
      const memo = await draftMemo(
        borrower.name,
        borrower.exposure,
        borrower.features,
      );
      setState({ phase: "ready", memo, approved: false });
    } catch (cause) {
      const message =
        cause instanceof ApiError && cause.status === 0
          ? "Backend unreachable. Start the API to draft a memo."
          : cause instanceof Error
            ? cause.message
            : "Failed to draft memo.";
      setState({ phase: "error", message });
    }
  }

  function approve() {
    setState((prev) =>
      prev.phase === "ready" ? { ...prev, approved: true } : prev,
    );
  }

  return (
    <div className="panel">
      <div className="p-head" style={{ alignItems: "center" }}>
        <div className="p-title">GenAI credit memo — draft</div>
        <span className="memo-badge">
          <span className="dot" />
          Officer approval required
        </span>
      </div>

      {state.phase === "idle" && (
        <div className="memo-empty">
          <span>
            Draft an early-warning credit memo for {borrower.name} from the live
            score and reason codes.
          </span>
          <button className="btn btn-primary" onClick={generate}>
            Draft credit memo
          </button>
        </div>
      )}

      {state.phase === "loading" && (
        <div className="state">
          <span className="spinner" />
          Drafting memo…
        </div>
      )}

      {state.phase === "error" && (
        <div className="memo-empty">
          <div className="state error" style={{ padding: 0 }}>
            {state.message}
          </div>
          <button className="btn btn-outline" onClick={generate}>
            Retry
          </button>
        </div>
      )}

      {state.phase === "ready" && (
        <>
          <div className="memo-body">{state.memo.body}</div>
          {state.memo.sources.length > 0 && (
            <div className="memo-sources">
              Sources:{" "}
              {state.memo.sources.map((src, index) => (
                <span key={src}>
                  {index > 0 ? " · " : ""}
                  <a href={src} target="_blank" rel="noreferrer">
                    {src}
                  </a>
                </span>
              ))}
            </div>
          )}
          <div className="memo-meta">
            <span>Generated by {state.memo.generated_by}</span>
          </div>
          <div className={`memo-status ${state.approved ? "ok" : ""}`}>
            {state.approved
              ? `Approved by Credit Officer · logged to audit trail · ${borrower.account}`
              : state.memo.status}
          </div>
          <div className="memo-actions">
            <button
              className="btn btn-primary"
              onClick={approve}
              disabled={state.approved}
            >
              {state.approved ? "Approved ✓" : "Approve (human-in-loop)"}
            </button>
            <button className="btn btn-outline" onClick={generate}>
              Re-draft
            </button>
          </div>
        </>
      )}
    </div>
  );
}
